// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_-I0_YXsX6vB2VqtRkjy2Vm3C3_H7kN0',
    appId: '1:1037636677726:web:3211fe1c6fe64e6c8ac4cf',
    messagingSenderId: '1037636677726',
    projectId: 'clisense',
    authDomain: 'clisense.firebaseapp.com',
    databaseURL: 'https://clisense-default-rtdb.firebaseio.com',
    storageBucket: 'clisense.firebasestorage.app',
    measurementId: 'G-SMT8YYS6W2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1dg0rQiQjw0J9Eyu0L7_pImuAnXV3QgU',
    appId: '1:1037636677726:android:f019f0466eb047c58ac4cf',
    messagingSenderId: '1037636677726',
    projectId: 'clisense',
    databaseURL: 'https://clisense-default-rtdb.firebaseio.com',
    storageBucket: 'clisense.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuvOB2igsLfUwtZS8ravB4xvjvHEhKvqY',
    appId: '1:1037636677726:ios:e36c113e3bd727458ac4cf',
    messagingSenderId: '1037636677726',
    projectId: 'clisense',
    databaseURL: 'https://clisense-default-rtdb.firebaseio.com',
    storageBucket: 'clisense.firebasestorage.app',
    androidClientId: '1037636677726-85jk2nluif3kr8cukelqahdtvso7oj1m.apps.googleusercontent.com',
    iosClientId: '1037636677726-4lm3b54s2o8kd6cvrvboa36ulooaphsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.clisence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuvOB2igsLfUwtZS8ravB4xvjvHEhKvqY',
    appId: '1:1037636677726:ios:e36c113e3bd727458ac4cf',
    messagingSenderId: '1037636677726',
    projectId: 'clisense',
    databaseURL: 'https://clisense-default-rtdb.firebaseio.com',
    storageBucket: 'clisense.firebasestorage.app',
    androidClientId: '1037636677726-85jk2nluif3kr8cukelqahdtvso7oj1m.apps.googleusercontent.com',
    iosClientId: '1037636677726-4lm3b54s2o8kd6cvrvboa36ulooaphsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.clisence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_-I0_YXsX6vB2VqtRkjy2Vm3C3_H7kN0',
    appId: '1:1037636677726:web:add7bc77e6e8c21d8ac4cf',
    messagingSenderId: '1037636677726',
    projectId: 'clisense',
    authDomain: 'clisense.firebaseapp.com',
    databaseURL: 'https://clisense-default-rtdb.firebaseio.com',
    storageBucket: 'clisense.firebasestorage.app',
    measurementId: 'G-918FB55Y61',
  );

}